"""
Codex / OpenAI Codex Installer
================================
Produces:

  AGENTS.md              ← root instructions file (also read by Cursor, Zed, etc.)
  .codex/<standard>.md   ← one file per code standard

References:
  https://platform.openai.com/docs/codex
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import List

from .base import BaseInstaller


class CodexPluginInstaller(BaseInstaller):
    """Installs code style rules for OpenAI Codex / Codex CLI."""

    def build(self, standards: List[Path]) -> dict[str, str]:
        file_map: dict[str, str] = {}
        today = date.today().isoformat()

        std_list = "\n".join(f"- {s.name}" for s in standards)
        rule_refs: list[str] = []

        for std_dir in standards:
            slug = self.slugify(std_dir.name)
            rule_rel = f".codex/{slug}.md"
            file_map[rule_rel] = self._build_rule_file(std_dir, slug, today)
            rule_refs.append(f"- .codex/{slug}.md  ({std_dir.name})")

        refs_block = "\n".join(rule_refs)
        file_map["AGENTS.md"] = f"""\
# Code Style & Standards
<!-- Auto-generated by code-style-installer on {today} -->

## Standards in this project

{std_list}

## Rule files

{refs_block}

## General Reminders

- Follow the applicable standard for every file you create or modify.
- Do not mix conventions from different standards in the same file.
"""
        return file_map

    def _build_rule_file(self, std_dir: Path, slug: str, today: str) -> str:
        display_name = std_dir.name.replace("-", " ").replace("_", " ").title()
        body = self.read_standard(std_dir)
        if not body:
            body = f"_No content found in {std_dir}._"

        return f"""\
# {display_name}
<!-- Auto-generated on {today} from {std_dir.name} -->

{body}
"""

    def reload_hint(self) -> None:
        print("\n--- Codex Reload ---")
        print("  Re-run your Codex CLI session or API call — AGENTS.md is read")
        print("  automatically at the start of every request.")
        print()
